### ISSUE TITLE
GUI crashes when trying to load improper data

### ISSUE THREAD

**Issue by schaubia** [3fon3fonov/exostriker#101]
Hi,
While exploring the Data inspector menu of the tool, I've found accidentally found out that the GUI crashes when clicking on Export button if there is no data to export, or when trying to load any other than RV data with the 'Load to ES' button (for example transit data). I think it will be more convenient if this triggers an error message in the Stdout/Stderr panel rather than inexpectedly closing the program.
This also happens when trying to open an  RVbank file from the drop-down menu.

**Comment by 3fon3fonov** [comment]
Thanks! I re-wrote the save_DataInspector_data() function, and now I hope it works correctly. Please git pull, test, and let me know.

**Comment by schaubia** [comment]
Thanks, the first two issues are fixed now, however the last one remains: GUI crashes when trying to open an RVbank file from the drop-down menu.

**Comment by 3fon3fonov** [comment]
On my side, the HARPS_RVBank data file imports work most of the time. I encountered a couple of bugs during random import, which I think are easy to fix.  However, keep in mind that the HARPS_RVBank files are quite special, and they follow the format from here: https://www2.mpia-hd.mpg.de/homes/trifonov/HARPS_RVBank.html

Generally, the “import HARPS RVBank file” is quite obsolete, and it dates back to version 0.01. Please do not use it. Better use the Data Inspector and load files from there. I will get back to this problem when HARPS RVBank ver.02 is released (I hope very soon). 

Yet, I would like to know if you are indeed trying to import RVBank formatted file or something else. The exact error will be also appreciated.  (use the -debug argument).

**Comment by 3fon3fonov** [comment]
Nevertheless, I inserted some simple logic to check if the imported file is indeed RVBank file. Please try, and let me know if the ES still crashes.

**Comment by schaubia** [comment]
Hi, I tried it with a .dat file, exported from the RVbank. It seems that it is a data format/shape issue.
Here is the error message:
<class 'ValueError'> not enough values to unpack (expected 2, got 1) <traceback object at 0x7f58c5e38c00>
===== 2022.04.17 04:04:35 =====
Traceback (most recent call last):
  File "/home/schaubia/exostriker/exostriker/exostriker/gui.py", line 5757, in showDialog_RVbank_input_file
    fit.add_RVbank_dataset(self.file_from_path(input_files[0]), str(input_files[0]), split = False)
  File "/home/schaubia/exostriker/exostriker/exostriker/lib/RV_mod/__init__.py", line 3788, in add_RVbank_dataset
    num_cols,num_rows = HARPS_RVBank_data.shape
ValueError: not enough values to unpack (expected 2, got 1)

I've pulled again but it still closes inexpectedly.

**Comment by 3fon3fonov** [comment]
Hm... I cannot confirm this bug. Git pull one more time, try again, and if you still have problems, please send me the file in question.

**Comment by schaubia** [comment]
Now fixed. I pulled one more time and now receive the error message: Not a HARPS_RVBank file!. Thanks!
