### ISSUE TITLE
"wotan not found" issue

### ISSUE THREAD

**Issue by schaubia** [3fon3fonov/exostriker#103]
I've installed the latest version of the tool per instructions; however, I received this "wotan not found" message. I've tried to copy the wotan folder under the local Exo-Striker directory, but this approach didn't work.
It actually seems to be a Numba issue undercover, because after I commented out part of the code in the "__init__.py" file as outlined in the attached image, the tool seems to be working. 
![Screenshot 2022-05-01 10^%25^%16](https://user-images.githubusercontent.com/49037163/166157440-3137a5cd-0c0f-4b85-a919-d3faf5ebcd2d.png)

**Comment by 3fon3fonov** [comment]
I see... So wotan needs numpy=>1.21. What are your numba/numpy version? mine are:
>>> import numpy as np
>>> np.__version__
'1.22.3'
>>> import numba as nb
>>> nb.__version__
'0.52.0'
>>> 


See also https://github.com/3fon3fonov/exostriker/issues/100

**Comment by schaubia** [comment]
import numpy

numpy.__version__
Out[2]: '1.22.0'

import numba

numba.__version__
Out[4]: '0.55.1'

**Comment by schaubia** [comment]
Mine are;

numpy.__version__
'1.22.0'

numba.__version__
'0.55.1'

**Comment by 3fon3fonov** [comment]
if, e.g.,

```
$ sudo pip3 uninstall numba
$ sudo pip3 install numba==0.52
```

Everything will work.... 


I included in the setup.py 

```
   install_requires_py_ver=[
    "numpy>=1.21",
    "numba==0.52",...
```

Anyway, I will get back to this problem ASAP. Let's keep this issue open for other users.

**Comment by 3fon3fonov** [comment]
I think this bug is not happening any more, with the new python3.10+ and newest numpy version. Closing.
