### ISSUE TITLE
Orbital evolution controls missing from GUI

### ISSUE THREAD

**Issue by schaubia** [3fon3fonov/exostriker#105]
Hi, after the latest git pull, I've found out that all the additional controls in the Orb. Evol. tab (Plots panel) are missing. These include the radio buttons, as well as the drop-down menus from which to, chose resonance angles, etc. I don't have any error messages for missing packages neither in the Stdout/StdErr window nor in the terminal.  I am attaching a snip of the GUI
![Capture](https://user-images.githubusercontent.com/49037163/171040990-67aa142e-54f4-43ee-965e-383d9c2ca7f3.PNG)
.

**Comment by schaubia** [comment]
Here are the currently installed packages:
r_gui.py -debug
scipy==1.2.1
qtconsole==4.4.1
PyQt5==5.15.6
pathos==0.2.8
numpy==1.21.5
matplotlib==3.3.1
jupyter==1.0.0
jupyter-client==5.2.3
ipykernel==4.9.0
emcee==3.1.1
corner==2.2.1
celerite==0.3.1
wotan==1.10
ttvfast==0.3.0
dynesty==1.1
transitleastsquares==1.0.24
You are running a development version of the Exo-Striker (ver. 0.70). 
              
This version is almost full, but there are still some parts of the tool, which are in a 'Work in progress' state. Please, 'git pull' regularly to be up to date with the newest version.

Here you can get some more information from the tool's workflow, stdout/strerr, and piped results.
running stability with: symba
stability with: symba done!
--- 1.5228691101074219 seconds ---
^C

**Comment by 3fon3fonov** [comment]
Oh no! :) These were moved in the Plot Opt. tab.  Double-click in the plot tab (i.e., Period evol.) and you will be navigated to the plot controls. We should add this info in the Readthedocs manual.

**Comment by schaubia** [comment]
What a miss on my side. I´ll update the corresponding manual parts.

**Comment by 3fon3fonov** [comment]
OK then, I am closing. Thanks!
