### ISSUE TITLE
Problem with the installation of PYQt5 on macOS Monterey

### ISSUE THREAD

**Issue by ThanosOAA** [3fon3fonov/exostriker#107]
I'm running a Mac with the operating system macOS Monterey(version 12.4) and a M2 chip. And I have trouble installing PYQt5 as well as Exostriker. The feedback code can be seen from the screenshot below. 
My python version is python-3.8.10-macos11, and my gfortran version is gfortran-ARM-12.1-Monterey. 
Thank you!
<img width="1397" alt="Screen Shot 2022-08-12 at 12 10 33 PM" src="https://user-images.githubusercontent.com/111050124/184838300-d73eb5f7-54b2-4bfb-bf69-4f2a10490e41.png">

**Comment by 3fon3fonov** [comment]
Please try:

% pip3 show pyqt5

and report the output.


You can try to remove pyqt5:

% pip3 uninstall pyqt5

and then 

% pip3 install pyqt5==5.15.4


Also, I would recommend to "google" the problem, since this is likely a specific problem on MontereyOS/M2 chip configuration, and not the Exo-Striker. I would be happy to solve it thought because more like you will start experiencing the problem.

Let's keep in touch and solve the issue.

**Comment by ThanosOAA** [comment]
![image](https://user-images.githubusercontent.com/111050124/185764707-49dba787-9585-447e-9209-cacefaee8687.png)
Thank you for your solution! However, I tried the code you suggested, but still didn't work.

**Comment by 3fon3fonov** [comment]
Please, try the solution proposed by Luis U. here:

https://stackoverflow.com/questions/70248787/unable-to-install-pyqt5-with-pip

**Comment by ThanosOAA** [comment]
![image](https://user-images.githubusercontent.com/111050124/185795655-f666dbc8-5bf2-49c9-ae4b-ca2f630b006d.png)![image](https://user-images.githubusercontent.com/111050124/185796219-bee5bde8-43a5-41b0-a280-dbabcdc6320e.png)
Problem solved! Thank you for your advice Professor!

**Comment by 3fon3fonov** [comment]
Ok you have installed the PyQt5, but still it says "Something went wrong". Thus, Exo-Striker is still not working. I suspect you have "permission" issues. Above you install with pip, later with pip3. It is unclear to me if you install in your user directory. Please take a simple git clone and do the following:

In a user directory:
$ git clone https://github.com/3fon3fonov/exostriker
$ cd exostriker
$ python3.8 exostriker_gui.py -debug

It it powers without problems/warnings, then try to open RV file and play with the GUI. If everything is fine then good! Please report the solution here so you can help other people with the same problem. Else, we have more work to do....
