### ISSUE TITLE
gfortran issue when starting Exostriker on MacOS

### ISSUE THREAD

**Issue by jvglr** [3fon3fonov/exostriker#112]
I am experiencing a similar issue as described in issues #96 and #75. When running exostriker, I get the following:

`New source code available: Updating Keplerian Simplex
New source code available: Updating Keplerian L-M
New source code available: Updating N-body Simplex
New source code available: Updating N-body L-M
New source code available: Updating Mixed Simplex

Something went wrong!!! 

Perhaps you do not have user permission to compile code in the Exo-Striker directory?
Or perhaps, you do not have 'gfortran' installed? 

Trying 

$ gfortran -v 

returned:

[['Using', 'built-in', 'specs.'], ['COLLECT_GCC=gfortran'], ['COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/12.2.0/bin/../libexec/gcc/x86_64-apple-darwin21/12/lto-wrapper'], ['Target:', 'x86_64-apple-darwin21'], ['Configured', 'with:', '../configure', '--prefix=/usr/local/opt/gcc', '--libdir=/usr/local/opt/gcc/lib/gcc/current', '--disable-nls', '--enable-checking=release', '--with-gcc-major-version-only', '--enable-languages=c,c++,objc,obj-c++,fortran', '--program-suffix=-12', '--with-gmp=/usr/local/opt/gmp', '--with-mpfr=/usr/local/opt/mpfr', '--with-mpc=/usr/local/opt/libmpc', '--with-isl=/usr/local/opt/isl', '--with-zstd=/usr/local/opt/zstd', "--with-pkgversion='Homebrew", 'GCC', "12.2.0'", '--with-bugurl=https://github.com/Homebrew/homebrew-core/issues', '--with-system-zlib', '--build=x86_64-apple-darwin21', '--with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk'], ['Thread', 'model:', 'posix'], ['Supported', 'LTO', 'compression', 'algorithms:', 'zlib', 'zstd'], ['gcc', 'version', '12.2.0', '(Homebrew', 'GCC', '12.2.0)']]    

If 'gfortran' is not found, please install it and try again. Else, please open a GitHub issue here:

https://github.com/3fon3fonov/exostriker/issues
        
You do not have openAI installed, so You cannot use the GPT-3 chatboot Try $ pip install openai
qt.qpa.window: <QNSWindow: 0x7f9053cc4c00; contentView=<QNSView: 0x7f9053cc4230; QCocoaWindow(0x600003183bd0, window=QWidgetWindow(0x600012c35980, name="MainWindowClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.`

The GUI still starts up and I can load transit data and create fits, but loading RV data causes Exostriker to crash and return
`Abort trap: 6`

I'm on macOS Monterey 12.6.3, using Python 3.9.16 and gfortran 12.2.0. 
I'm using Anaconda with conda version 23.3.1, Anaconda client version 1.11.2 and Anaconda Navigatior version 2.4.0.

So far I have tried:

Running Exostriker with sudo (no change)

As described in the thread of #96, I tried running 
$ bash install_f77_opt.sh -O3
in the exostriker directory. This returned the following:

`Installing the Fortran routines for a first time!
 
 
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libSystem.tbd' for architecture x86_64
collect2: error: ld returned 1 exit status
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libSystem.tbd' for architecture x86_64
collect2: error: ld returned 1 exit status
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libSystem.tbd' for architecture x86_64
collect2: error: ld returned 1 exit status
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libSystem.tbd' for architecture x86_64
collect2: error: ld returned 1 exit status
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libSystem.tbd' for architecture x86_64
collect2: error: ld returned 1 exit status`

I also tried uninstalling Exostriker and reinstalling it with 
`sudo pip3 install git+https://github.com/3fon3fonov/exostriker`
as suggested in the thread to issue #96. However, this immediately produced a warning not to use sudo pip. Now, whenever I try to run Exostriker, it does not start up anymore, but produces several warnings and then crashes:
`objc[11934]: Class QMacAutoReleasePoolTracker is implemented in both /Users/jakobvogler/anaconda3/lib/libQt5Core.5.15.2.dylib (0x10e8ca388) and /Users/jakobvogler/anaconda3/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x13eda8198). One of the two will be used. Which one is undefined.
objc[11934]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/jakobvogler/anaconda3/lib/libQt5Core.5.15.2.dylib (0x10e8ca400) and /Users/jakobvogler/anaconda3/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x13eda8210). One of the two will be used. Which one is undefined.
objc[11934]: Class KeyValueObserver is implemented in both /Users/jakobvogler/anaconda3/lib/libQt5Core.5.15.2.dylib (0x10e8ca428) and /Users/jakobvogler/anaconda3/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x13eda8238). One of the two will be used. Which one is undefined.
objc[11934]: Class RunLoopModeTracker is implemented in both /Users/jakobvogler/anaconda3/lib/libQt5Core.5.15.2.dylib (0x10e8ca478) and /Users/jakobvogler/anaconda3/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x13eda8288). One of the two will be used. Which one is undefined.
objc[11934]: Class QCocoaPageLayoutDelegate is implemented in both /Users/jakobvogler/anaconda3/lib/libQt5PrintSupport.5.15.2.dylib (0x13b9e9478) and /Users/jakobvogler/anaconda3/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x13c448540). One of the two will be used. Which one is undefined.
objc[11934]: Class QCocoaPrintPanelDelegate is implemented in both /Users/jakobvogler/anaconda3/lib/libQt5PrintSupport.5.15.2.dylib (0x13b9e94f0) and /Users/jakobvogler/anaconda3/lib/python3.9/site-packages/PyQt5/Qt5/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x13c4485b8). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x600002078410) is not the object's thread (0x600002075160).
Cannot move to target thread (0x600002078410)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen, webgl.

Abort trap: 6
`
I'm slowly running out of ideas for what to try. Any suggestions would be welcome.

**Comment by 3fon3fonov** [comment]
It seems your gfortan is not working. All you need to do is to try to reinstall gfortran/gcc and try:

` $ bash install_f77_opt.sh -O3 `

Until it exits without error.

For MacOS, if you use "brew" I would probably try the following:

```
$ brew upgrade llvm
$ brew upgrade gcc
$ sudo rm -rf /Library/Developer/CommandLineTools
$ xcode-select --install
```
Let me know if this fixes the gfortran problem. Any other problems should be discussed in another "Issue"

**Comment by jvglr** [comment]
Thanks, the second approach fixed it! I've been able to fix the other issues by deleting and reinstalling Anaconda as well, so now it runs without any error messages.

**Comment by 3fon3fonov** [comment]
Great! Then, I am closing this issue.
