### ISSUE TITLE
RV bank HARPS disconnect ?? 29/08/2023 11:08AM (UT)

### ISSUE THREAD

**Issue by MTalafha82** [3fon3fonov/exostriker#116]
just to aske the users if they faced same issue , RV bank HARPS disconnect ??

**Comment by 3fon3fonov** [comment]
The error is "No internet connection, or no connection to the HARPS RVBank!!!"

It seems there is some problem with the MPIA servers where the RVBanks are hosted. It should be restored soon, I hope... The new RVBank ver.02, will be optional download in the future Exo-Striker versions so this (very rare) problem will be resolved soon for good.


T.

**Comment by MTalafha82** [comment]
Thank you ,
