### ISSUE TITLE
Missing required packages

### ISSUE THREAD

**Issue by melissa-hobson** [3fon3fonov/exostriker#124]
On a clean installation, the following packages had to be installed separately: pathos, PyQt5, tdqm.

**Comment by 3fon3fonov** [comment]
HI Mellisa, on which OS? and how do you install? 

git clone and then:

```
python3 -m build
pip install .
```

?

**Comment by melissa-hobson** [comment]
Ubuntu, git clone, and then following the installation instructions:
pip install build
cd exostriker
python3 -m build
pip install .

**Comment by 3fon3fonov** [comment]
Interesting.... exacly on Ubuntu works perfectly fine on my side. 

In your case, when you type python3, which python3 version is actually called? The new Exo-Striker requires python 3.10+.

I will give it a try on a clean ubuntu and I will report.

**Comment by melissa-hobson** [comment]
python3 calls python3.11.5

**Comment by 3fon3fonov** [comment]
@melissa-hobson I did a clean check and I cannot confirm this problem on Ubuntu 22.04. I had other problems installing PyQt5 with python3.11/pip3.11, but I am unsure if this is related. At the moment I am running the Exo-Striker on a fresh system Ubuntu22.04 with python3.10, which was installed without any drama.  

Are you now running on python3.11? Can you please confirm? Also, do a git pull (as aways).

**Comment by melissa-hobson** [comment]
It runs fine now - I probably messed up something in the install :joy:

**Comment by 3fon3fonov** [comment]
Ok then I am closing, but let us keep an eye on this possible issue.
