### ISSUE TITLE
gui structure

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/exostriker#13]
My feeling:
- [x] (1) The tabs RV, RVo-c,... should be over (not under) Timeseries, Periodo search,...
     -> Data first then analsysis.
- [x] (2) DFT should be in the same line as period search.
- [ ] (3) "phase plots" should be in the same line as timeseries
- [ ] (4) extraplots is basically a second plot window. May it should be possible to show here the same content possibilities as in the first.
- [ ] (5) "Limits and Priors" for RV should be in the same line as "offset and jitter"
- [ ] (6) "Plot opt." should be closer to the plots.

`RV`, `RV o-c`, `Transit`, ...
`Time Series`, `Period search`, `Phase plots`, ... `Plot opt.`

**Comment by mzechmeister** [comment]
I just wanted to post the same thing, again. So, I still support this.
I added (6), I understand it is a setting, but it is not a model setting. Hence, it can be moved away from its current position towards the plot row.
It will be easier to find. The drawback will be, that one has to go back and forth to see the style modifications.

**Comment by 3fon3fonov** [comment]
Some work has been done. The rest with lower priority.

**Comment by 3fon3fonov** [comment]
I am closing this because:

3 - is meant to be shown only in the extra plot widget.
4 - is https://github.com/3fon3fonov/exostriker/issues/47
5 - I don't see a need for a change
6 - I don't see a need for a change
