### ISSUE TITLE
What to do if ES does not work after a new git-pull

### ISSUE THREAD

**Issue by 3fon3fonov** [3fon3fonov/exostriker#25]
If your Exo-Striker stops working after a git-pull to a newer version (e.g. cannot load .vels file or "Fit" crashes, etc.), the first thing to try is to re-run the bash scrip and generate new Fortran binaries (it takes a minute!). 

It is very likely that I changed something in the Fortran binaries, which are not pulled to your local machine. You need to compile them locally.

This will be fixed when I make a setup.py/pip install in the RVmod, and when all Fortran routines are translated to f2py. But since I am still working on the Fortran code this problem may occur from time to time.

**Comment by mzechmeister** [comment]
Related to #16.
After `git pull`, the binaries should be recompiled.
A `makefile` or a `setup.py` would be good, then there is no need to go through the install script.

**Comment by 3fon3fonov** [comment]
I am on it, but I need to fix some other more important problems first....

**Comment by 3fon3fonov** [comment]
I added an auto-check for old versions. If you have old binaries, at start, the ES will automatically compile the new from the recent git-pull. Thus I think this issue could be closed, but I will keep it open for a while.
