### ISSUE TITLE
Swift library not compiling? (dyld: Library not loaded: @rpath/./libgfortran.3.dylib)

### ISSUE THREAD

**Issue by jvines** [3fon3fonov/exostriker#53]
Hi @3fon3fonov ,

After updating to the latest version, the GUI opens after installing but I get the following message:
```
Something went wrong!!! Most likely the swift library was updated and now you 
            need to recompile it. E.g. use: 
                
               $ bash installers/XXXXX_install.sh 
```

The output from bash installers/MAC_OS_install.sh is in the attached [out.log](https://github.com/3fon3fonov/exostriker/files/4009028/out.log) file.

**Comment by jvines** [comment]
I digged a little deeper and the problem is that ```result1``` from line 5973 returns ```
rv.run_command_with_timeout('./lib/fr/loglik_kep -version', 1,output=True)
([['dyld:', 'Library', 'not', 'loaded:', '@rpath/libgfortran.3.dylib'], ['Referenced', 'from:', '/Users/jvines/github/exostriker/./lib/fr/loglik_kep'], ['Reason:', 'image', 'not', 'found']], 1)
```

I really don't know what's going on and why the installation seemingly fails nor how to fix that dyld library not loaded problem

**Comment by 3fon3fonov** [comment]
Hi @jvines ,

did you ran 

`$ bash installers/MAC_OS_install.sh`

AFTER you see the warning?

If yes, did you try to power the GUI once again?


What is happening is that you had an old fortran binaries and swift library, that are
compiled on your MAC. When you do "git pull" you only download the source files.
Thus, "exostriker" tells you to recompile binaries. This usually works very well.

To be on the safe side, you can completely remove the old exostriker and git clone a new one.
e.g.:

$ git clone https://github.com/3fon3fonov/exostriker

then, e.g. for a MacOS installation:

$ cd exostriker
$ bash installers/MAC_OS_install.sh

Then, if your gfortran works fine, you should be able to run the tool with no problems.

Let me know!

**Comment by jvines** [comment]
Hi @3fon3fonov ,

Indeed, I tried re-running the installer after seeing the warning and I also tried a clean clone of the repository, to no avail.. :(

**Comment by 3fon3fonov** [comment]
Do you run 
`python3 es_gui.py
`
INSIDE inside the exostriker root directory? This is the only way it works at the moment.

E.g. 
$ cd exostriker
$ python3 es_gui.py 

if yes, there might be some problem with your gfortran.
 please make a 

$ gfortran -v

and post the optput.

**Comment by jvines** [comment]
Yes. I run it from the root directory.

Here's my gfortran -v output

```
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/anaconda3/bin/../libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper
Target: x86_64-apple-darwin11.4.2
Configured with: ./configure --prefix=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-gxx-include-dir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/gcc/include/c++ --bindir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin --datarootdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share --libdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib --with-gmp=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpfr=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-mpc=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-isl=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-cloog=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --with-boot-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --with-stage1-ldflags='-Wl,-headerpad_max_install_names -Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib -Wl,-L/usr/lib' --enable-checking=release --with-tune=generic --disable-multilib
Thread model: posix
gcc version 4.8.5 (GCC)
```

**Comment by 3fon3fonov** [comment]
here is mine (on Mac OS, which works without problems):

Annas-MacBook-Air:trifon tito$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/9.2.0_2/libexec/gcc/x86_64-apple-darwin19/9.2.0/lto-wrapper
Target: x86_64-apple-darwin19
Configured with: ../configure --build=x86_64-apple-darwin19 --prefix=/usr/local/Cellar/gcc/9.2.0_2 --libdir=/usr/local/Cellar/gcc/9.2.0_2/lib/gcc/9 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 9.2.0_2' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
Thread model: posix
gcc version 9.2.0 (Homebrew GCC 9.2.0_2)

Do you see the difference? Try to upgrade. Also, do you have an Anaconda3 install or you have a system Python2/3 ? I do have system install via the MacOS bash script. You may try also 

`bash installers/anaconda_install.sh 
`

This might update your anaconda packages.

Let me know.

**Comment by jvines** [comment]
I tried with the anaconda installer and it still didn't work.

I'll see if changing the compiler to the one installed with homebrew fixes the problem

( I really don't know where all those placeholds come from :s)

**Comment by 3fon3fonov** [comment]
Ok I hope it works! Keep me updated! I guess if you update your system (i.e. gfortran, gcc, etc.) all will work fine, but I am still not sure where is the problem. 

Also, please let me know next time:

* version of Mac OS you have,
* which python you are using.

**Comment by jvines** [comment]
I'll try tomorrow after I wake up, but for now, I'm using OS X Mojave 10.14.6 and python 3.7.1

**Comment by jvines** [comment]
Hi @3fon3fonov ,

It seems that changing the fortran compiler did the trick!

Thank you very much :)

**Comment by 3fon3fonov** [comment]
Great! 

The actual error output from the Fortran code is:

dyld: Library not loaded: @rpath/./libgfortran.3.dylib

I looked for this error in "Google", and it seems that many people ran into this error when using the gfortran in the Anaconda Python Distribution. I wonder if updating your anaconda will fix the issue?


I am closing this issue. You are welcome to reopen or post a new issue
if you encounter another problem!
