### ISSUE TITLE
TypeError: 'QStatusBar' object is not callable

### ISSUE THREAD

**Issue by zhexingli** [3fon3fonov/exostriker#56]
I got this error message when loading my rv data:

Traceback (most recent call last):
  File "./lib/word_processor_es/word_processor_es.py", line 332, in file_open
    self.setStatusBar(self.status(path))
TypeError: 'QStatusBar' object is not callable

Is it something I need to download or it's already included in the package but the installation process missed it?

**Comment by 3fon3fonov** [comment]
This really harmless error that does not affect your overall experience with the Exo-Striker. It comes from the "text editor" widget. I was trying to improve it and I forgot to remove a small code. 

This makes me wonder what would be the connection with the RV data? I hope you are not loading data with the "text editor"? You always load it from here (when using the GUI).
![ES_RVdata](https://user-images.githubusercontent.com/44244057/76142289-72624a00-606c-11ea-9c83-84a164b9c5b7.png)


Anyway, please "git pull" the new version, which is free of this small bug.

**Comment by 3fon3fonov** [comment]
Dear @zhexingli,

I am closing this issue because it was fixed. If you ever encounter a similar problem please feel free to re-open.

**Comment by zhexingli** [comment]
Oh I see thank you!
