### ISSUE TITLE
Listing of rms for each instrument

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/exostriker#61]
Would be nice to see somewhere the rms of each instrument.

**Comment by 3fon3fonov** [comment]
There is no room on the GUI panel. I will make a jupyter function that can call this output. 

However, I found space for an "Info button":
![rms_wrms](https://user-images.githubusercontent.com/44244057/84546892-a5b71380-ad02-11ea-9df1-fb1853d03349.png)

Is that OK? Of course, more output should be displayed in the "info" window, but I just starting.

Let me know.

**Comment by mzechmeister** [comment]
Fine for me.
