### ISSUE TITLE
The X11 connection broke (error 1). Did the X11 server die?

### ISSUE THREAD

**Issue by 3fon3fonov** [3fon3fonov/exostriker#64]
This is one very serious bug, which I am trying to solve for some time. 

It appears when a locally saved session is exported to cluster/server for MCMC/NS run using many CPUs. 

The session loads on the local machine and on the server with no problem. When the MCMC/NS is done the new saved session with the samples is exported via e.g. scp/rsync and most of the time works fine. However, somewhat randomly, some output sessions with MCMC/NS cannot be opened anymore.

At import at the GUI am getting:

The X11 connection broke (error 1). Did the X11 server die?

Any help with this will be highly appreciated!

**Comment by 836304831** [comment]
I have got the same problem when I run pyqt application on mac + docker environment.

**Comment by rishabhc6499** [comment]
I got the same issue when I run ROS- rosrun turtlesim turtlesim_node on mac+docker environment.

**Comment by 3fon3fonov** [comment]
This is some strange memory problem with python. The solution seems to be to execute the Exo-Striker script under Ipython/jupiter schell. E.g.

trifonov@lnx:~$ python3.8                         
Python 3.8.0 (default, Feb 25 2021, 22:10:10) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> %run your_script.py

and when is done 

>>>exit()


then the saved session can be re-opened with the Exo-Striker (at least on my side).

**Comment by 3fon3fonov** [comment]
@LuighiV, I agree, but this problem is really out of my competence. I spend days figuring out what is going on, and at some point, I give up. The only "terminal/server" solution I found is listed above. I got indications from many people (including you) that this is a valid workaround, which makes me happy. However, I will seek some professional help on this matter...

**Comment by 3fon3fonov** [comment]
Closing, since this bug is no longer relevant with the f2py compiled rvmod_*.so 

Please feel free to reopen if it emerges again on versions 0.85+
