### ISSUE TITLE
How can I select a periodogram peak and add it as a planet?

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/exostriker#7]
I see the `autofit` button, which is good and very automatic.
But manual prewhitening seems to be cumbersome.

**Comment by 3fon3fonov** [comment]
This is planned and will be done soon. Same applies for the transit TLS period search... there you can see I start implementing this but I got distracted by other things. Will keep you updated when is done.

**Comment by 3fon3fonov** [comment]
Mathias, hi!

I added a "adopt best Period" button to the o-c RV GLS periodograms. I think it make sense this button to be only on the o-c, since the GLS periodogram to the plain time series never change. I made a couple of tests on the Eta Ceti system and it seems to work very well with only one data set. For more than one data sets,
which may have very different RV offsets, it is advisable first to run a fit with no planets (just press "fit") in order to adjust the zero point offsets. From there, inspect the combined o-c GLS and add planets as you like.

**Comment by 3fon3fonov** [comment]
Actually this does not solve your initial question "How can I select a periodogram peak and add it as a planet?" To select an arbitrary peak will require some more work from my side and maybe from yours (within the gls.py). At the moment you can adopt only the best (strongest) peak as a planet.

**Comment by mzechmeister** [comment]
Ok, at least it works for the highest peak.
It would be good the mark the highest peak with dots as in our starreports.

You could add a selection box with frequency candidates.
Or would it be possible to select the peak directly from the plot?

**Comment by 3fon3fonov** [comment]
> It would be good the mark the highest peak with dots as in our starreports.
I could add this option.

> You could add a selection box with frequency candidates.
if you press "Print Info" you get the 10 strongest peaks. Of course this is static. 
I will try to add an interactive selection in future.

> Or would it be possible to select the peak directly from the plot?
Yes, probably is possible to get signal from the cross-hair, but this will require some coding. 
I will keep it in mind.

**Comment by mzechmeister** [comment]
All peaks are marked with the same symbol. One cannot see which one is the highest.
Also often an alias peak is chosen, which was not marked at all.

**Comment by mzechmeister** [comment]
The plotted periodogram also looks undersampled.

**Comment by 3fon3fonov** [comment]
I need more details about the problem(s). 

> All peaks are marked with the same symbol. 

Well, I cannot go into such detail at the moment. 

> One cannot see which one is the highest.

Zoom in with the mouse buttons.

> Also often an alias peak is adopted, which was not marked at all.

Can you give an example? Maybe the marked peaks are not exacly the same as the one adopted for planets. Can you confirm that even if: Plot opt. --> GLS/TLS --> avoid possible 1d aliases == True, the adopted planet peak is an alias? The marked peaks, I think, are so far only for plotting. 

> The plotted periodogram also looks undersampled.

Models param. --> GLS/TLS param. --> GLS oversamp fact. = 10 ?
