### ISSUE TITLE
Orbital Evolution

### ISSUE THREAD

**Issue by myilmazzz** [3fon3fonov/exostriker#70]
Hi,

When I run Orb. Evol button I am getting an error message like this; 
"running stability with: symba something went wrong!!! No output generated". 

In addition, I see this message in the terminal; 
"mkdir: cannot create directory ‘./run’: File exists"

I want to check orbital evolution for one target star that host two possible planets.

**Comment by myilmazzz** [comment]
> The Exo-Striker is creating the "run" temp. directory runs the evolution, reads the output files, and then, once the integration is done all is removed. In your case, the Exo-Striker creates the "run' directory, but the integration is not executed and I guess it fails to remove the directory.
> 
> The bottom line is that you are likely not able to compile the Swift library. Hence:
> "running stability with: symba something went wrong!!! No output generated".
> 
> try to run in the /exostriker directory:
> 
> $ bash install_swift.sh
> 
> and report the output.
> 
> Also please provide info about your OS, Fortran compiler and how did you install the tool (git clone or pip install).

Thank you for your reply,

I have compiled the install_swift.sh according to your comment and i think that everything is ok now. In the terminal, i see still the message "mkdir: cannot create directory ‘./run’: File exists" Does it a normal message?

by the way, my OS is Linux Mint 20. I have created a conda environment named exostriker and i installed exostriker into it using pip install.

**Comment by 3fon3fonov** [comment]
OK. Go to /exostriker/stability and
remove the directory /run

e.g.

$ rm -r run

then try again.


Are you sure you have full permission to write in your anaconda directory? I think this should not be a problem, but if the problem presist check your permission

**Comment by 3fon3fonov** [comment]
Any progress?

**Comment by myilmazzz** [comment]
Hi,

your comments solved my problems and everything is work well now. Thank you again.

**Comment by schaubia** [comment]
Hi, I have the same problem. Ater compiling the swift library I still cannot run the orb. evolution, I have the following output in the terminal:

bash install_swift.sh 
 
Installing the swift N-body lib for a first time!
 
install_swift.sh: line 11: csh: command not found
 
Compiling Symba/mvs and other N-body routines for a first time!



The tool is installed via the clone method, and I'm using Ubuntu 20.04.

**Comment by schaubia** [comment]
PS: If the tool is not running in debug mode, the terminal output when trying to run orb. evolution is:
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5867, resource id: 6291566, major code: 40 (TranslateCoords), minor code: 0
