### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/exostriker#72]
Installing with `python3 setup.py install --user`
I get

```
...
copying exostriker.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    license="MIT"
  File "~/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
...
File "~/.local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by 3fon3fonov** [comment]
Hi Mathias, 

I have never seen this error before, and the Exo-Striker installs well with setup.py on my side. A quick "google" suggests that you may have some old .pyc files, perhaps compiled with python2.7 which you are trying to re-use? Try to remove everything old from the old Exo-Striker (or move it somewhere else). Alternatively: 

(i) update your "setuptools"
(ii) install the Exo-Striker via pip (pip3 install git+https://github.com/3fon3fonov/exostriker --user)
(iii) simply git-clone and use the Exo-Striker locally (i.e.
$ git clone https://github.com/3fon3fonov/exostriker
$ cd exostriker 
$ python3 exostriker_gui.py
(iv) migrate to python3.8

**Comment by 3fon3fonov** [comment]
Mathias, any progress on this?

**Comment by 3fon3fonov** [comment]
Due to inactivity this is closed. If needed, please re-open.
