### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by sai-33** [3fon3fonov/exostriker#74]
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

**Comment by 3fon3fonov** [comment]
When this happens: is the $DISPLAY variable set? Are you able to open e.g. 'xterm'? 

Googling this error leads to many open threads and possible solutions. Yet, these problems are not related to the Exo-Striker code in any way. I will be happy to assist, but I need more info, like what OS you are using, what Python, how did you install the Exo-Striker, and how did you end up in this error?

**Comment by sai-33** [comment]
I am using ubuntu 
python version -3.9
I installed exostriker: firstly copying the whole code and making a new repo in my GitHub and cloned it. when entering the code python exostriker_gui.py. ubuntu giving this error.
NOTE: I copied the code because in ubuntu it required the username and password of your's GitHub account.

**Comment by 3fon3fonov** [comment]
Thanks for this info! I am unsure why you need my password and usrname. If you go after a "git clone" all you need is:

$ git clone https://github.com/3fon3fonov/exostriker
$ cd exostriker
$ python exostriker_gui.py

At first boot, the Exo-Striker will install the needed fortran libraries and will start normally. After that it should power with no problems.


Can you try the above, but use the -debug argument, i.e.:

$ python exostriker_gui.py -debug


This must output the installed libraries and a possible cause of the error. For instance, my output on Ubuntu 18.04.5 with Python3.8, leads to:

```
trifonov@lnx:~/git/exostriker$ python3.8 exostriker_gui.py -debug
qtconsole==4.7.7
wotan==1.7
ttvfast==0.3.0
dynesty==1.0.1
transitleastsquares==1.0.24
celerite==0.4.0
corner==2.1.0
pathos==0.2.6
ipykernel==5.3.4
jupyter-client==6.1.7
jupyter==1.0.0
scipy==1.6.1
PyQt5==5.15.4
numpy==1.20.2
matplotlib==3.3.1
emcee==3.0.2
You are running a demo version of the Exo-Striker (ver. 0.57). 

```

**Comment by 3fon3fonov** [comment]
OK.... I think this must go in another direction to make sure your PyQt5 and other libs are installed correctly. You can either install my setup above, e.g. 
```

$ sudo pip3 install qtconsole==4.7.7
$ sudo pip3 install wotan==1.7
....
$ sudo pip3 install emcee==3.0.2
```

or, install the tool via pip with will automatically install all the needed packages.

`$ sudo pip3 install git+https://github.com/3fon3fonov/exostriker`

and then in a shell, just type:

`$ exostriker`

(or just power the tool in the git clone directory, after opening a new shell).


It could be also a Python3.9 related problem.... I never tested the Exo-Striker fresh install on a 3.9 version. Generally, I would recommend Python3.8 but first, try the above.

**Comment by sai-33** [comment]
Giving same Error

**Comment by 3fon3fonov** [comment]
In the shell where you power the GUI, type:

$ export QT_DEBUG_PLUGINS=1

then, e.g.

$ python3 exostriker_gui.py


Let me know if this fixes the problem on your system.

**Comment by sai-33** [comment]
![Screenshot (250)](https://user-images.githubusercontent.com/72378635/120760625-f20deb80-c531-11eb-899a-77a8552fca95.png)
![Screenshot (249)](https://user-images.githubusercontent.com/72378635/120760631-f33f1880-c531-11eb-830e-5ded73ccd5fe.png)
![Screenshot (248)](https://user-images.githubusercontent.com/72378635/120760632-f3d7af00-c531-11eb-8018-8aff5959a3af.png)

GIVING THIS ERROR

**Comment by 3fon3fonov** [comment]
Well, next step is to reinstall pyqt5. 

make sure ALL pyqt5 libraries are removed, e.g.

$ sudo pip3 uninstall PyQt5 PyQt5-Qt PyQt5-Qt5 PyQt5-sip pyqt5-tools

them for example:

$ sudo pip3 install PyQt5==5.15.4 

$ sudo pip3 install PyQt5-Qt==5.15.2

$ sudo pip3 install PyQt5-Qt5==5.15.2

$ sudo pip3 install PyQt5-sip==12.8.1

$ sudo pip3 install pyqt5-tools==5.15.0.1.7.1


then try again, but always start the tool from a fresh bash shell

**Comment by sai-33** [comment]
giving same error

**Comment by sai-33** [comment]
Ran Successfully.
Thanks for your assistance.

**Comment by sai-33** [comment]
One more small doubt is that is exostriker take fits files for radial velocity (fits file from HARPS data)

**Comment by sai-33** [comment]
![Screenshot (253)](https://user-images.githubusercontent.com/72378635/120816636-8eee7a00-c56e-11eb-8b42-5bdce6283f90.png)

BUT giving This Error

**Comment by 3fon3fonov** [comment]
I opened new issues for your additional questions, see above. Please close these if your problems are solved/questions answered.
