### ISSUE TITLE
Suggestion: Add option to show aliases besides the cross-hair also for activity indicators

### ISSUE THREAD

**Issue by JonasKemmer** [3fon3fonov/exostriker#78]
Hey Trifon,

title says it all: it would be nice if you could also add the option to show aliases besides the cross-hair for the activity indicator periodograms.

Best regards,
Jonas

**Comment by 3fon3fonov** [comment]
I see... The aliases are shown only to the GLS and MLP RV periodograms, right? If that's what you mean, I will make this option, sure.

**Comment by JonasKemmer** [comment]
Exactly, aliases are currently only shown in GLS and MLP of RV periodograms. It would be nice to also have them in the periodograms for activity indicators. Of course, I can also load the indicators in the RV panel to see aliases, but not multiple ones at the same time, which I like about the indicator panel.

**Comment by 3fon3fonov** [comment]
Check now, please. However, the control is done from Plot Opt. --> GLS/MPL/TLS/, and then the RV tab. I will move this to a separate section when I have time, but generally not should work as you want it.

Let me know if you are happy.

**Comment by JonasKemmer** [comment]
Great! Thanks a lot!
