### ISSUE TITLE
Gaussian priors are not saved at sessions.

### ISSUE THREAD

**Issue by sgongar** [3fon3fonov/exostriker#83]
Saved sessions stores all data except gaussians priors for planets. When you open a saved session these data are not present.

**Comment by 3fon3fonov** [comment]
Thanks for reporting this bug. I wonder how this was left undetected for so long! Anyway, now the export of the priors should work. Please check and report if the new version of the tool fixes your problems.

**Comment by sgongar** [comment]
A made a few tests and it's working, thank you so much!
