### ISSUE TITLE
Dataset upload error

### ISSUE THREAD

**Issue by aberrico** [3fon3fonov/exostriker#85]
I can't upload more than 3 datasets.  I'm running exostriker in debug mode on ubuntu 20.4 OS.
The message I'm getting when I try to upload a fourth dataset is as follows:

$ python3 exostriker_gui.py -debug
scipy==1.4.1
qtconsole==4.6.0
numpy==1.18.1
matplotlib==3.1.3
jupyter==1.0.0
jupyter-client==5.3.4
ipykernel==5.1.4
wotan==1.9
ttvfast==0.3.0
dynesty==1.0.1
transitleastsquares==1.0.24
celerite==0.4.0
corner==2.2.1
emcee==3.0.2
pathos==0.2.7
PyQt5==5.15.4
You are running a demo version of the Exo-Striker (ver. 0.57).
             
This version is almost full, but there are still some parts of the tool, which are in a 'Work in progress' state. Please, 'git pull' regularly to be up to date with the newest version.

Here you can get some more information from the tool's workflow, stdout/strerr, and piped results.
<class 'IndexError'> list index out of range <traceback object at 0x7f4b0b60e7d0>
===== 2021.10.04 17:10:04 =====
Traceback (most recent call last):
  File "/home/adriana/exostriker/exostriker/gui.py", line 4195, in showDialog_RV_input_file
    fit.add_dataset(self.file_from_path(input_files[0]), str(input_files[0]),0.0,1.0)
  File "/home/adriana/exostriker/exostriker/lib/RV_mod/__init__.py", line 3524, in add_dataset
    path =  copy_file_to_datafiles(path)
  File "/home/adriana/exostriker/exostriker/lib/RV_mod/functions.py", line 1318, in copy_file_to_datafiles
    if line[0].startswith("#"):
IndexError: list index out of range

Abortado (`core' generado)

**Comment by 3fon3fonov** [comment]
Ok, I can confirm the bug. The problem seems to be that you have an empty line in your file. E.g.,

2459324.903139229 -6.183 0.034
2459342.850646396 -6.221 0.024
~
~
~

This was not a problem before, so I need to investigate. I will push a fix asap, meanwhile, your quick fix will be to remove the empty line(s). Please let me know if this is a potential fix.
