### ISSUE TITLE
Detrending with GP crashes using wotan==1.10 in Python3.8 and macOS

### ISSUE THREAD

**Issue by ccifuentesr** [3fon3fonov/exostriker#90]
Detrending transit data using Gaussian Processes causes Exostriker to crash when using wotan==1.10 in Python3.8 (macOS 11.6.1). Downgrading to, e.g., wotan==1.7, fixes this issue.

**Comment by 3fon3fonov** [comment]
Works fine on Ubuntu 18.10, Python3.8 and Wotan==1.10.

Again Mac OS-related problems? Anaconda3?  


I saw when you install wotan==1.7, there was some new installation of numba. Please try to revert to wotan==1.10 and report if that fixed the issue. Else, go back to wotan==1.7 until I figure out what is going on.

**Comment by ccifuentesr** [comment]
Indeed, reverting back to wotan==1.10 now yields no errors.

**Comment by 3fon3fonov** [comment]
Wait... but is it working now with 1.10?

**Comment by ccifuentesr** [comment]
It is working, yes, looks like the numba was somehow reinstalled/updated, and that was the issue.

**Comment by 3fon3fonov** [comment]
Ok, then please list your wotan depnedencies versions for reverence. I.e. 

numba==x.xx
numpy==
scipy==

Thanks.

**Comment by ccifuentesr** [comment]
PyQt5==5.15.4
numpy==1.20.3
wotan==1.10
numba==0.54.1
scipy==1.7.2
pathos==0.2.8
ttvfast==0.3.0
dynesty==1.1
transitleastsquares==1.0.24
celerite==0.4.0
corner==2.2.1
emcee==3.1.1
qtconsole==5.1.1
ipykernel==6.4.1
jupyter-client==7.0.5
jupyter==1.0.0
matplotlib==3.3.1
